### ISSUE TITLE
continuous rebuild loop

### ISSUE THREAD

**Issue by techieeliot** [nano-react-app/nano-react-app#18] opened 2020-07-17 01:07 UTC
![Npm Start GIF-source](https://user-images.githubusercontent.com/19453294/87737185-e5f53000-c79f-11ea-9eb3-35f12dc1b707.gif)

**Comment by adrianmcli** [comment] 2020-07-17 01:57
@techieeliot your gif is not loading

**Comment by techieeliot** [comment] 2020-07-17 02:04
@adrianmcli 

https://giphy.com/gifs/Xf1HIUZsITD4qoFxDy

**Comment by adrianmcli** [comment] 2020-07-17 02:09
Thanks, I just tried it right now and I could not reproduce. Would you like to throw up a reproduction repo?

**Comment by techieeliot** [comment] 2020-07-17 02:26
Here is my freeCodeCamp random-quote-machine repo that I'm working out of. 

https://github.com/techieeliot/random-quote-machine

**Comment by adrianmcli** [comment] 2020-07-17 02:28
@techieeliot I think something might be wrong with your environment, because I can't reproduce the problem with your repo either (it runs perfectly fine on my machine).

**Comment by techieeliot** [comment] 2020-07-17 03:04
Ok, thanks @adrianmcli. I'll try to reboot my machine and see if that helps.

**Comment by adrianmcli** [comment] 2020-07-17 03:09
Yeah sorry I couldn't help! I'm going to close this for now. If you have any new information about how I can help, just post it here and I can re-open.

**Closed as completed by adrianmcli** 2020-07-17 03:09 UTC

**Comment by techieeliot** [comment] 2020-07-17 14:41
@adrianmcli I rebooted and cloned the repo again. It's good now. Thanks!

**Comment by techieeliot** [comment] 2020-07-17 17:22
Well, I think I discovered what's creating the issue. When I tried adding App.css directly into the index.html, then I think I ended up in an infinite loop of re-renders with React. 

@adrianmcli what method would you recommend for styling my nano react app? I must be misunderstanding how to do that properly. 

Thanks for helping me pinpoint the problem! 

[My app is live right now on netlify - https://random-quote-machine-techieeliot.netlify.app/](https://random-quote-machine-techieeliot.netlify.app/) (without any of my styling 😢 ). Hopefully, I can get that fixed with your guidance.

**Comment by techieeliot** [comment] 2020-07-17 18:47
Hey @adrianmcli I figured it out using styled-components. 

When I was trying to `import './App.css'` in index.js that was not working for some reason. Any hints as to why that wouldn't work?

**Comment by adrianmcli** [comment] 2020-07-17 20:30
`import './App.css'` should just work out of the box. The resulting project you get is just a regular Parcel project. Maybe you can ask over on their repo?

Link: https://github.com/parcel-bundler/parcel/issues

**Comment by techieeliot** [comment] 2020-07-19 12:42
Thanks! I'll create an issue over there.
