### ISSUE TITLE
broken ?

### ISSUE THREAD

**Issue by scdba** [nano-react-app/nano-react-app#8] opened 2019-11-18 16:45 UTC
get this while using 
npx nano-react-app my-app

(node:77164) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink '/<REDACTED>/my-app/package-lock.json'
(node:77164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Amaranthos** [comment] 2019-11-19 05:29
I am seeing this error too, when executing `npx nano-react-app my-app` in the packages directory of yarn workspaces monorepo.

Would suggest this is occurring when the script tries to delete the `package-lock.json`

**Comment by mgreasly** [comment] 2019-11-21 01:45
Yes, it's only because of the package-lock.json file missing. I think the project is actually ready to go at that point as it's just the clean up.

**Comment by adrianmcli** [comment] 2019-11-21 02:28
Ah sorry, it was taken away due to https://github.com/adrianmcli/nano-react-app-template/issues/6 and https://github.com/adrianmcli/nano-react-app-template/pull/7

Need to remove that from the script, I suppose.

**Comment by adrianmcli** [comment] 2019-11-21 07:58
Fixed by https://github.com/adrianmcli/nano-react-app/pull/10

**Closed as completed by adrianmcli** 2019-11-21 07:58 UTC

**Comment by adrianmcli** [comment] 2019-11-21 08:02
Just tested to make sure it works.

**Comment by fluffybane** [comment] 2019-12-10 12:52
Started seeing this error today. As @mgreasly suggested before the project is still generated correctly so this isn't a major issue.

**Comment by adrianmcli** [comment] 2019-12-10 14:44
@FluffyBane are you sure you have the latest version of `nano-react-app`? Because this is fixed and I also just tried it now.

**Comment by fluffybane** [comment] 2019-12-13 11:00
I'm fairly sure but not 100% 
If I'm using this command: 
> npx nano-react-app myapp

shouldn't that be fetching the latest version? I don't think I've actually got it installed locally. 

Will check after work though. Cheers for the reply.

**Comment by adrianmcli** [comment] 2019-12-13 18:03
> shouldn't that be fetching the latest version? I don't think I've actually got it installed locally.

I don't think this is the case, see this SO [post](https://stackoverflow.com/questions/50605219/difference-between-npx-and-npm). It first takes whatever you have currently installed in path.

**Comment by fluffybane** [comment] 2019-12-14 14:12
> It first takes whatever you have currently installed in path.

Ahh. Okay this is interesting. It seems that even if I uninstall the local version which was v0.1.2, if I run the npx command again it will only fetch v0.1.2 and reinstall that. 

So the issue is unrelated but any idea why npx wouldn't fetch the latest version of nano-react-app?
